rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'bazel-build'
    - 'integration-tests'
    - 'unit-tests'
    - 'lint'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi-go
    permission: push
  - team: actools
    permission: admin
  - team: actools-go
    permission: push
